apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tenant3-apiserver
  namespace: tenant-clusters
  labels:
    app: tenant3-control-plane
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: tenant3-control-plane
      monitoring: enabled
  endpoints:
    - port: api
      interval: 30s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'apiserver_request_total|apiserver_request_duration_seconds.*|apiserver_current_inflight_requests|process_cpu_seconds_total|process_resident_memory_bytes|go_goroutines|etcd_request_duration_seconds.*|apiserver_storage_.*|kine_.*'
          action: keep
