apiVersion: kamaji.clastix.io/v1alpha1
kind: TenantControlPlane
metadata:
  name: tenant1
  namespace: tenant-clusters
spec:
  controlPlane:
    deployment:
      replicas: 3
    service:
      serviceType: NodePort
      port: 6443
      nodePort: 30443

  kubernetes:
    version: v1.26.1

  networkProfile:
    serviceCIDR: 10.96.0.0/12
    podCIDR: 10.244.0.0/16
    dnsServiceIPs:
      - 10.96.0.10
