apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kamaji
  namespace: argocd
spec:
  description: Kamaji control plane and tenant clusters

  sourceRepos:
    - '*'

  destinations:
    - namespace: kamaji-system
      server: https://kubernetes.default.svc
    - namespace: tenant-clusters
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc   # add this

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
